server:
  port: 8081
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mengfanwu/spring-cloud-config-repo.git
          searchPaths:
          username: mengfanwu
          password: meng0430
      label: master
